language: node_js

# Opt-in to Travis's container infrastructure. This potentially makes builds less flaky, and easier to debug.
# - https://docs.travis-ci.com/user/reference/trusty/#container-based-with-sudo-false
# - https://docs.travis-ci.com/user/common-build-problems/#troubleshooting-locally-in-a-docker-image
# - https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/#what-benefits-does-this-new-infrastructure-have
sudo: false

branches:
  # Only run Travis on:
  #   A) Commits made directly to the `master` branch (i.e., merged PRs); and
  #   B) PRs that will eventually be merged into `master`.
  # This prevents excessive resource usage and CI slowness.
  only:
    - master
    - feat/select-new

before_install:
  # Source the scripts to export their env vars. See https://superuser.com/a/176788/62792
  - source scripts/travis-env-vars.sh

install:
  - if has_testable_files; then npm install; fi
  # Noisy output, but useful for debugging npm package dependency version issues:
  #- npm ls

after_script:
  # Prevent Travis job logs from getting truncated early.
  # See https://github.com/travis-ci/travis-ci/issues/6421#issuecomment-238137337
  - sleep 5

matrix:
  include:

  - node_js: 8
    env:
      - TEST_SUITE=lint
    script:
      - if has_testable_files; then npm run lint; else log_untestable_files; fi

  - node_js: 8
    env:
      - TEST_SUITE=build
    script:
      - if has_testable_files; then npm run build; else log_untestable_files; fi

  - node_js: 8
    env:
      - TEST_SUITE=unit
    addons:
      sauce_connect: true
    script:
      - if has_testable_files; then npm run test:unit && npm run posttest; else log_untestable_files; fi
    after_success:
      - codecov

  - node_js: 8
    env:
      - TEST_SUITE=closure
      - CLOSURE=1
    script:
      - if has_testable_files; then npm run test:closure; else log_untestable_files; fi

  - node_js: 8
    env:
      - TEST_SUITE=site-generator
    script:
      - if has_testable_files; then npm run test:site; else log_untestable_files; fi

  - node_js: 8
    env:
      - TEST_SUITE=screenshot
    git:
      depth: 200
    before_install: # Override global settings
      # Source the scripts to export their env vars. See https://superuser.com/a/176788/62792
      - source scripts/travis-env-vars.sh
      - source test/screenshot/infra/commands/travis.sh
    script:
      - if has_testable_files; then npm run screenshot:test; else log_untestable_files; fi
