language: node_js

# Force Travis CI to run jobs in VMs instead of Docker containers.
# - https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
# - https://docs.travis-ci.com/user/reference/trusty/#fully-virtualized-via-sudo-required
sudo: required

branches:
  # Only run Travis on:
  #   A) Commits made directly to the `master` branch (i.e., merged PRs); and
  #   B) PRs that will eventually be merged into `master`.
  # This prevents excessive resource usage and CI slowness.
  only:
    - master
    - develop
    - /feature\/.*/

before_install:
  # Source the scripts to export their env vars. See https://superuser.com/a/176788/62792
  - source scripts/travis-env-vars.sh

install:
  - if has_testable_files; then npm ci; fi
  # Noisy output, but useful for debugging npm package dependency version issues:
  #- npm ls

after_script:
  # Prevent Travis job logs from getting truncated early.
  # See https://github.com/travis-ci/travis-ci/issues/6421#issuecomment-238137337
  - sleep 5

matrix:
  include:
  - node_js: 10
    env:
      - TEST_SUITE=screenshot
    git:
      depth: 200
    before_install: # Override global settings
      # Source the scripts to export their env vars. See https://superuser.com/a/176788/62792
      - source scripts/travis-env-vars.sh
      - source test/screenshot/infra/commands/travis.sh
    script:
      - if has_testable_files; then npm run screenshot:test; else log_untestable_files; fi
