name: MDC Release (Pull Request)

# This workflow creates or updates (if already exists) a pull request with new
# version bump on every commit to master.

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**/*.ts'
      - 'packages/**/*.scss'
      - '**/package*.json'
      - '**/.npmignore'
      - '**/*.md'

jobs:
  release-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Sync with origin
        run: |
          git pull --rebase origin master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          npm install
      - name: Bump version
        run: |
          npx lerna version --conventional-commits --no-git-tag-version --no-push --yes
      - name: Create PR
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Release"
          author: GitHub Action <action@users.noreply.github.com>
          title: "chore: Release"
          body: |
            This PR was opened by [release][1] GitHub action.
            When you're ready to do a release, you can merge this and release
            action will automatically publishes to npm registry.
            If you're not ready to do a release yet, that's fine, whenever you
            add more commits to master, this PR will be updated.

            [1]: http://github.com/material-components/material-components-web/tree/master/.github/workflows/release-pull-request.yml
          branch: chore/release
